In [1]:
!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.45 --force-reinstall --no-cache-dir -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.7/36.7 MB 106.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 176.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 201.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 253.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 141.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 220.4 MB/s eta 0:00:00
  Building wheel for llama-cpp-python (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.4 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.4 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.4 which is incompatible.
cupy-cuda12x 13.3.0 requires numpy<2.3,>=1.22, but you have numpy 2.3.4 which is incompatible.

In [2]:
!pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2025.10.5)

In [3]:
import pandas as pd
from huggingface_hub import hf_hub_download
from llama_cpp import Llama
import json

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
data = pd.read_csv("/content/drive/MyDrive/LLM/restaurant_reviews.csv")

In [6]:
data.head()

,restaurant_ID,rating_review,review_full
0,FLV202,5,"Totally in love with the Auro of the place, re..."
1,SAV303,5,Kailash colony is brimming with small cafes no...
2,YUM789,5,Excellent taste and awesome decorum. Must visi...
3,TST101,5,I have visited at jw lough/restourant. There w...
4,EAT456,5,Had a great experience in the restaurant food ...

In [7]:
data['review_full'][3]

'I have visited at jw lough/restourant. There were a first class service at lough, specially Ms.laxmi  who were superbed for handling the client need, me and my family lots enjoyed her specialty in the manner, and Laxmi is a very very good in the client service, I hope when I will come against I would definitely serve from Ms. Laxmi and she is wonderful girl in that service. See you again Ms. Laxmi for the your best service which I have received from you at jw lough/resourant. Thank you JW Marriott Hotel at Atrocity, Delhi'

In [8]:
data.shape

(20, 3)

In [9]:
data.isnull().sum()

restaurant_ID    0
rating_review    0
review_full      0
dtype: int64

In [10]:
model_name_or_path = "TheBloke/Llama-2-13B-chat-GGUF"
model_basename = "llama-2-13b-chat.Q5_K_M.gguf"

In [11]:
model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

llama-2-13b-chat.Q5_K_M.gguf:   0%|          | 0.00/9.23G [00:00<?, ?B/s]

In [12]:
Llama_llm = Llama(
    model_path=model_path,
    n_threads=2,
    n_batch=512,
    n_gpu_layers=43,
    n_ctx=4096,
)

llama_model_loader: loaded meta data with 19 key-value pairs and 363 tensors from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-13B-chat-GGUF/snapshots/4458acc949de0a9914c3eab623904d4fe999050a/llama-2-13b-chat.Q5_K_M.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 5120
llama_model_loader: - kv   4:                          llama.block_count u32              = 40
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 13824
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 40
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 40
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 17
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type q5_K:  241 tensors
llama_model_loader: - type q6_K:   41 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V2
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_head           = 40
llm_load_print_meta: n_head_kv        = 40
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 5120
llm_load_print_meta: n_embd_v_gqa     = 5120
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 13824
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 13B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 13.02 B
llm_load_print_meta: model size       = 8.60 GiB (5.67 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.28 MiB
llm_load_tensors: offloading 40 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 41/41 layers to GPU
llm_load_tensors:        CPU buffer size =   107.42 MiB
llm_load_tensors:      CUDA0 buffer size =  8694.21 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =  3200.00 MiB
llama_new_context_with_model: KV self size  = 3200.00 MiB, K (f16): 1600.00 MiB, V (f16): 1600.00 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =    19.04 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   368.02 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    10.00 MiB
llama_new_context_with_model: graph splits (measure): 3
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
Model metadata: {'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.context_length': '4096', 'general.name': 'LLaMA v2', 'llama.embedding_length': '5120', 'llama.feed_forward_length': '13824', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'llama.attention.head_count': '40', 'tokenizer.ggml.bos_token_id': '1', 'llama.block_count': '40', 'llama.attention.head_count_kv': '40', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '17'}

In [13]:
model_name_or_path = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
model_basename = "mistral-7b-instruct-v0.2.Q6_K.gguf"

In [14]:
model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
)

mistral-7b-instruct-v0.2.Q6_K.gguf:   0%|          | 0.00/5.94G [00:00<?, ?B/s]

In [15]:
mistral_llm = Llama(
    model_path=model_path,n_ctx=1024)

llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from /root/.cache/huggingface/hub/models--TheBloke--Mistral-7B-Instruct-v0.2-GGUF/snapshots/3a6fbf4a41a1d52e415a4958cde6856d34b2db93/mistral-7b-instruct-v0.2.Q6_K.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mistral-7b-instruct-v0.2
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 18
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  21:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q6_K:  226 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q6_K
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 5.53 GiB (6.56 BPW)
llm_load_print_meta: general.name     = mistralai_mistral-7b-instruct-v0.2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size =  5666.09 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 1024
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =   128.00 MiB
llama_new_context_with_model: KV self size  =  128.00 MiB, K (f16):   64.00 MiB, V (f16):   64.00 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =    11.01 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    96.00 MiB
llama_new_context_with_model: graph splits (measure): 1
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
Model metadata: {'tokenizer.chat_template': "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}", 'tokenizer.ggml.add_eos_token': 'false', 'tokenizer.ggml.padding_token_id': '0', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.rope.freq_base': '1000000.000000', 'llama.context_length': '32768', 'general.name': 'mistralai_mistral-7b-instruct-v0.2', 'tokenizer.ggml.add_bos_token': 'true', 'llama.embedding_length': '4096', 'llama.feed_forward_length': '14336', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'tokenizer.ggml.bos_token_id': '1', 'llama.attention.head_count': '32', 'llama.block_count': '32', 'llama.attention.head_count_kv': '8', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '18'}
Using chat template: {{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}
Using chat eos_token:
Using chat bos_token:

In [16]:

def generate_llama_response(instruction, review):
    system_message = """
        [INST]<<SYS>>
        {}
        <</SYS>>[/INST]
    """.format(instruction)


    prompt = f"{review}\n{system_message}"


    response = Llama_llm(
        prompt=prompt,
        max_tokens=1024,
        temperature=0,
        top_p=0.95,
        repeat_penalty=1.2,
        top_k=50,
        stop=['INST'],
        echo=False,
        seed=42,
    )


    response_text = response["choices"][0]["text"]
    return response_text

In [17]:

def extract_json_data(json_str):
    try:

        json_start = json_str.find('{')
        json_end = json_str.rfind('}')

        if json_start != -1 and json_end != -1:
            extracted_sentiment = json_str[json_start:json_end + 1]  # Extract the JSON object
            data_dict = json.loads(extracted_sentiment)
            return data_dict
        else:
            print(f"Warning: JSON object not found in response: {json_str}")
            return {}
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return {}

In [18]:
data_1 = data.copy()

In [19]:
instruction_1 = """
    You are an AI analyzing restaurant reviews. Classify the sentiment of the provided review into the following categories:
    - Positive
    - Negative
    - Neutral
"""

In [20]:
data_1['model_response'] = data_1['review_full'].apply(lambda x: generate_llama_response(instruction_1, x))

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      83.62 ms /   151 runs   (    0.55 ms per token,  1805.85 tokens per second)
llama_print_timings: prompt eval time =    1124.71 ms /   237 tokens (    4.75 ms per token,   210.72 tokens per second)
llama_print_timings:        eval time =    8514.61 ms /   150 runs   (   56.76 ms per token,    17.62 tokens per second)
llama_print_timings:       total time =   10237.56 ms /   387 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      61.57 ms /    98 runs   (    0.63 ms per token,  1591.76 tokens per second)
llama_print_timings: prompt eval time =     776.29 ms /   307 tokens (    2.53 ms per token,   395.47 tokens per second)
llama_print_timings:        eval time =    5497.85 ms /    97 runs   (   56.68 ms per token,    17.64 tokens per second)
llama_print_timings:       total time =    6747.43 ms /   404 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      58.16 ms /   104 runs   (    0.56 ms per token,  1788.23 tokens per second)
llama_print_timings: prompt eval time =     411.97 ms /    97 tokens (    4.25 ms per token,   235.46 tokens per second)
llama_print_timings:        eval time =    5969.39 ms /   103 runs   (   57.96 ms per token,    17.25 tokens per second)
llama_print_timings:       total time =    6781.49 ms /   200 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      72.89 ms /   119 runs   (    0.61 ms per token,  1632.71 tokens per second)
llama_print_timings: prompt eval time =     566.96 ms /   207 tokens (    2.74 ms per token,   365.10 tokens per second)
llama_print_timings:        eval time =    7013.23 ms /   118 runs   (   59.43 ms per token,    16.83 tokens per second)
llama_print_timings:       total time =    8128.15 ms /   325 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      71.25 ms /   116 runs   (    0.61 ms per token,  1628.02 tokens per second)
llama_print_timings: prompt eval time =     605.96 ms /   244 tokens (    2.48 ms per token,   402.67 tokens per second)
llama_print_timings:        eval time =    7096.24 ms /   115 runs   (   61.71 ms per token,    16.21 tokens per second)
llama_print_timings:       total time =    8252.02 ms /   359 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      88.54 ms /   146 runs   (    0.61 ms per token,  1649.01 tokens per second)
llama_print_timings: prompt eval time =     818.81 ms /   287 tokens (    2.85 ms per token,   350.51 tokens per second)
llama_print_timings:        eval time =    9593.51 ms /   145 runs   (   66.16 ms per token,    15.11 tokens per second)
llama_print_timings:       total time =   11030.72 ms /   432 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      70.27 ms /   120 runs   (    0.59 ms per token,  1707.60 tokens per second)
llama_print_timings: prompt eval time =     835.35 ms /   293 tokens (    2.85 ms per token,   350.75 tokens per second)
llama_print_timings:        eval time =    8214.50 ms /   119 runs   (   69.03 ms per token,    14.49 tokens per second)
llama_print_timings:       total time =    9549.47 ms /   412 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      74.93 ms /   119 runs   (    0.63 ms per token,  1588.17 tokens per second)
llama_print_timings: prompt eval time =     569.77 ms /   132 tokens (    4.32 ms per token,   231.67 tokens per second)
llama_print_timings:        eval time =    8313.99 ms /   118 runs   (   70.46 ms per token,    14.19 tokens per second)
llama_print_timings:       total time =    9432.96 ms /   250 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      81.81 ms /   134 runs   (    0.61 ms per token,  1637.96 tokens per second)
llama_print_timings: prompt eval time =     578.76 ms /   134 tokens (    4.32 ms per token,   231.53 tokens per second)
llama_print_timings:        eval time =    9902.91 ms /   133 runs   (   74.46 ms per token,    13.43 tokens per second)
llama_print_timings:       total time =   11094.27 ms /   267 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      72.90 ms /   124 runs   (    0.59 ms per token,  1700.91 tokens per second)
llama_print_timings: prompt eval time =     599.31 ms /   133 tokens (    4.51 ms per token,   221.92 tokens per second)
llama_print_timings:        eval time =    9320.38 ms /   123 runs   (   75.78 ms per token,    13.20 tokens per second)
llama_print_timings:       total time =   10469.08 ms /   256 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      52.31 ms /    95 runs   (    0.55 ms per token,  1816.06 tokens per second)
llama_print_timings: prompt eval time =     601.84 ms /   133 tokens (    4.53 ms per token,   220.99 tokens per second)
llama_print_timings:        eval time =    7006.97 ms /    94 runs   (   74.54 ms per token,    13.42 tokens per second)
llama_print_timings:       total time =    7979.90 ms /   227 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      87.17 ms /   148 runs   (    0.59 ms per token,  1697.79 tokens per second)
llama_print_timings: prompt eval time =     585.48 ms /   133 tokens (    4.40 ms per token,   227.16 tokens per second)
llama_print_timings:        eval time =   10431.84 ms /   147 runs   (   70.96 ms per token,    14.09 tokens per second)
llama_print_timings:       total time =   11682.73 ms /   280 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     108.13 ms /   181 runs   (    0.60 ms per token,  1673.86 tokens per second)
llama_print_timings: prompt eval time =     569.24 ms /   129 tokens (    4.41 ms per token,   226.62 tokens per second)
llama_print_timings:        eval time =   12509.39 ms /   180 runs   (   69.50 ms per token,    14.39 tokens per second)
llama_print_timings:       total time =   13878.05 ms /   309 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      73.81 ms /   114 runs   (    0.65 ms per token,  1544.40 tokens per second)
llama_print_timings: prompt eval time =    1010.96 ms /   435 tokens (    2.32 ms per token,   430.29 tokens per second)
llama_print_timings:        eval time =    7831.44 ms /   113 runs   (   69.30 ms per token,    14.43 tokens per second)
llama_print_timings:       total time =    9448.22 ms /   548 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      64.53 ms /   103 runs   (    0.63 ms per token,  1596.11 tokens per second)
llama_print_timings: prompt eval time =    1580.25 ms /   606 tokens (    2.61 ms per token,   383.48 tokens per second)
llama_print_timings:        eval time =    7272.06 ms /   102 runs   (   71.29 ms per token,    14.03 tokens per second)
llama_print_timings:       total time =    9381.79 ms /   708 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      90.78 ms /   149 runs   (    0.61 ms per token,  1641.37 tokens per second)
llama_print_timings: prompt eval time =     876.81 ms /   347 tokens (    2.53 ms per token,   395.75 tokens per second)
llama_print_timings:        eval time =   10746.29 ms /   148 runs   (   72.61 ms per token,    13.77 tokens per second)
llama_print_timings:       total time =   12263.48 ms /   495 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      51.89 ms /    93 runs   (    0.56 ms per token,  1792.39 tokens per second)
llama_print_timings: prompt eval time =     881.33 ms /   351 tokens (    2.51 ms per token,   398.26 tokens per second)
llama_print_timings:        eval time =    6796.49 ms /    92 runs   (   73.87 ms per token,    13.54 tokens per second)
llama_print_timings:       total time =    8053.07 ms /   443 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      86.42 ms /   134 runs   (    0.64 ms per token,  1550.57 tokens per second)
llama_print_timings: prompt eval time =     998.82 ms /   415 tokens (    2.41 ms per token,   415.49 tokens per second)
llama_print_timings:        eval time =    9657.70 ms /   133 runs   (   72.61 ms per token,    13.77 tokens per second)
llama_print_timings:       total time =   11280.55 ms /   548 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      70.88 ms /   113 runs   (    0.63 ms per token,  1594.29 tokens per second)
llama_print_timings: prompt eval time =    1490.35 ms /   545 tokens (    2.73 ms per token,   365.69 tokens per second)
llama_print_timings:        eval time =    8189.72 ms /   112 runs   (   73.12 ms per token,    13.68 tokens per second)
llama_print_timings:       total time =   10235.39 ms /   657 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     111.24 ms /   171 runs   (    0.65 ms per token,  1537.26 tokens per second)
llama_print_timings: prompt eval time =     887.96 ms /   368 tokens (    2.41 ms per token,   414.43 tokens per second)
llama_print_timings:        eval time =   12223.66 ms /   170 runs   (   71.90 ms per token,    13.91 tokens per second)
llama_print_timings:       total time =   13901.28 ms /   538 tokens

In [21]:
data_1['model_response'].head()

0     Sure! Here's the sentiment analysis of the re...
1     Sure! Here's the sentiment analysis of the pr...
2     Sure, I can help you with that! Based on the ...
3     Sure! Here's the classification of the review...
4     Sure! Here's the sentiment analysis of the re...
Name: model_response, dtype: object

In [22]:
data.shape

(20, 3)

In [23]:
i = 2
print(data_1.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [24]:
print(data_1.loc[i, 'model_response'])

 Sure, I can help you with that! Based on the review you provided, I would classify it as:

Positive

Reason: The reviewer enjoyed their experience at the restaurant, mentioning that it has "excellent taste" and "awesome decorum." They also appreciated the "great service" provided by Subham Barnwal, which suggests that the staff was attentive and helpful. Overall, the review expresses a positive opinion of the restaurant.

In [25]:
def extract_sentiment(model_response):
    if 'positive' in model_response.lower():
        return 'Positive'
    elif 'negative' in model_response.lower():
        return 'Negative'
    elif 'neutral' in model_response.lower():
        return 'Neutral'

In [26]:
# applying the function to the model response
data_1['sentiment'] = data_1['model_response'].apply(extract_sentiment)
data_1['sentiment'].head()

0    Positive
1    Positive
2    Positive
3    Positive
4    Positive
Name: sentiment, dtype: object

In [27]:
data_1['sentiment'].value_counts()

sentiment
Positive    16
Negative     3
Neutral      1
Name: count, dtype: int64

In [28]:
final_data_1 = data_1.drop(['model_response'], axis=1)
final_data_1.head()

,restaurant_ID,rating_review,review_full,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive
4,EAT456,5,Had a great experience in the restaurant food ...,Positive

In [29]:
data_1 = data.copy()

In [30]:
#Defining the response funciton for Task 1.
def response_1(prompt,review):
    model_output = mistral_llm(
      f"""
      Q: {prompt}
      Review: {review}
      A:
      """,
      max_tokens=32,
      stop=["Q:", "\n"],
      temperature=0.01,
      echo=False,
    )

    temp_output = model_output["choices"][0]["text"]

    return temp_output

In [31]:
instruction_1 = """
    You are an AI analyzing restaurant reviews. Classify the sentiment of the provided review into the following categories:
    - Positive
    - Negative
    - Neutral
"""

In [32]:
data_1['model_response'] = data_1['review_full'].apply(lambda x: response_1(instruction_1, x))

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.54 ms /    32 runs   (    0.55 ms per token,  1824.61 tokens per second)
llama_print_timings: prompt eval time =    3066.45 ms /   218 tokens (   14.07 ms per token,    71.09 tokens per second)
llama_print_timings:        eval time =   27088.60 ms /    31 runs   (  873.83 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   30313.97 ms /   249 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.91 ms /    32 runs   (    0.59 ms per token,  1692.58 tokens per second)
llama_print_timings: prompt eval time =    2744.89 ms /   235 tokens (   11.68 ms per token,    85.61 tokens per second)
llama_print_timings:        eval time =   27860.44 ms /    31 runs   (  898.72 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   30764.63 ms /   266 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.65 ms /    32 runs   (    0.58 ms per token,  1715.45 tokens per second)
llama_print_timings: prompt eval time =    1828.75 ms /    34 tokens (   53.79 ms per token,    18.59 tokens per second)
llama_print_timings:        eval time =   27692.09 ms /    31 runs   (  893.29 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   29670.41 ms /    65 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.83 ms /    32 runs   (    0.56 ms per token,  1794.43 tokens per second)
llama_print_timings: prompt eval time =    2072.57 ms /   143 tokens (   14.49 ms per token,    69.00 tokens per second)
llama_print_timings:        eval time =   26974.27 ms /    31 runs   (  870.14 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   29189.26 ms /   174 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.77 ms /    32 runs   (    0.56 ms per token,  1801.19 tokens per second)
llama_print_timings: prompt eval time =    2236.76 ms /   169 tokens (   13.24 ms per token,    75.56 tokens per second)
llama_print_timings:        eval time =   27107.24 ms /    31 runs   (  874.43 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   29484.28 ms /   200 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.32 ms /    32 runs   (    0.57 ms per token,  1746.72 tokens per second)
llama_print_timings: prompt eval time =    2475.73 ms /   217 tokens (   11.41 ms per token,    87.65 tokens per second)
llama_print_timings:        eval time =   27209.09 ms /    31 runs   (  877.71 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   29828.44 ms /   248 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.39 ms /    32 runs   (    0.57 ms per token,  1740.36 tokens per second)
llama_print_timings: prompt eval time =    2472.06 ms /   215 tokens (   11.50 ms per token,    86.97 tokens per second)
llama_print_timings:        eval time =   27224.01 ms /    31 runs   (  878.19 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   29834.73 ms /   246 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.74 ms /    32 runs   (    0.59 ms per token,  1707.85 tokens per second)
llama_print_timings: prompt eval time =    1921.31 ms /    69 tokens (   27.85 ms per token,    35.91 tokens per second)
llama_print_timings:        eval time =   27113.65 ms /    31 runs   (  874.63 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   29185.37 ms /   100 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.41 ms /    32 runs   (    0.58 ms per token,  1737.90 tokens per second)
llama_print_timings: prompt eval time =    1894.74 ms /    67 tokens (   28.28 ms per token,    35.36 tokens per second)
llama_print_timings:        eval time =   27088.87 ms /    31 runs   (  873.83 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   29125.81 ms /    98 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.01 ms /    32 runs   (    0.56 ms per token,  1776.40 tokens per second)
llama_print_timings: prompt eval time =    1727.69 ms /    68 tokens (   25.41 ms per token,    39.36 tokens per second)
llama_print_timings:        eval time =   27110.01 ms /    31 runs   (  874.52 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   28979.16 ms /    99 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.44 ms /    32 runs   (    0.58 ms per token,  1735.17 tokens per second)
llama_print_timings: prompt eval time =    1714.02 ms /    65 tokens (   26.37 ms per token,    37.92 tokens per second)
llama_print_timings:        eval time =   28181.16 ms /    31 runs   (  909.07 ms per token,     1.10 tokens per second)
llama_print_timings:       total time =   30038.20 ms /    96 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.76 ms /    32 runs   (    0.56 ms per token,  1801.80 tokens per second)
llama_print_timings: prompt eval time =    1748.10 ms /    71 tokens (   24.62 ms per token,    40.62 tokens per second)
llama_print_timings:        eval time =   27624.37 ms /    31 runs   (  891.11 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   29507.74 ms /   102 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =       2.93 ms /     4 runs   (    0.73 ms per token,  1366.59 tokens per second)
llama_print_timings: prompt eval time =    1863.59 ms /    64 tokens (   29.12 ms per token,    34.34 tokens per second)
llama_print_timings:        eval time =    3398.16 ms /     3 runs   ( 1132.72 ms per token,     0.88 tokens per second)
llama_print_timings:       total time =    5285.19 ms /    67 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.52 ms /    32 runs   (    0.58 ms per token,  1728.05 tokens per second)
llama_print_timings: prompt eval time =    3764.11 ms /   354 tokens (   10.63 ms per token,    94.05 tokens per second)
llama_print_timings:        eval time =   28563.08 ms /    31 runs   (  921.39 ms per token,     1.09 tokens per second)
llama_print_timings:       total time =   32489.13 ms /   385 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =       1.68 ms /     3 runs   (    0.56 ms per token,  1788.91 tokens per second)
llama_print_timings: prompt eval time =   14216.60 ms /   526 tokens (   27.03 ms per token,    37.00 tokens per second)
llama_print_timings:        eval time =    1707.16 ms /     2 runs   (  853.58 ms per token,     1.17 tokens per second)
llama_print_timings:       total time =   15940.76 ms /   528 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.38 ms /    32 runs   (    0.57 ms per token,  1740.83 tokens per second)
llama_print_timings: prompt eval time =    2884.76 ms /   274 tokens (   10.53 ms per token,    94.98 tokens per second)
llama_print_timings:        eval time =   27635.70 ms /    31 runs   (  891.47 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   30672.19 ms /   305 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      20.56 ms /    32 runs   (    0.64 ms per token,  1556.65 tokens per second)
llama_print_timings: prompt eval time =    3441.96 ms /   284 tokens (   12.12 ms per token,    82.51 tokens per second)
llama_print_timings:        eval time =   28053.20 ms /    31 runs   (  904.94 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   31647.66 ms /   315 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.36 ms /    32 runs   (    0.57 ms per token,  1742.82 tokens per second)
llama_print_timings: prompt eval time =    3363.65 ms /   335 tokens (   10.04 ms per token,    99.59 tokens per second)
llama_print_timings:        eval time =   27369.17 ms /    31 runs   (  882.88 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   30882.24 ms /   366 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.84 ms /    32 runs   (    0.56 ms per token,  1794.02 tokens per second)
llama_print_timings: prompt eval time =    4469.97 ms /   462 tokens (    9.68 ms per token,   103.36 tokens per second)
llama_print_timings:        eval time =   27842.61 ms /    31 runs   (  898.15 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   32465.24 ms /   493 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.51 ms /    32 runs   (    0.58 ms per token,  1729.17 tokens per second)
llama_print_timings: prompt eval time =    3409.68 ms /   297 tokens (   11.48 ms per token,    87.10 tokens per second)
llama_print_timings:        eval time =   27645.93 ms /    31 runs   (  891.80 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   31205.10 ms /   328 tokens

In [33]:
data_1['model_response'].head()

0     This review expresses a very positive sentime...
1     Based on the given review, the sentiment can ...
2     The sentiment expressed in this review is pos...
3     Based on the given review, it can be classifi...
4     Based on the provided review, the sentiment c...
Name: model_response, dtype: object

In [34]:
i = 2
print(data_1.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [35]:
print(data_1.loc[i, 'model_response'])

 The sentiment expressed in this review is positive. The use of words like "excellent taste," "awesome decorum," "must visit," "g

In [36]:
def extract_sentiment(model_response):
    if 'positive' in model_response.lower():
        return 'Positive'
    elif 'negative' in model_response.lower():
        return 'Negative'
    elif 'neutral' in model_response.lower():
        return 'Neutral'

In [37]:
# applying the function to the model response
data_1['sentiment'] = data_1['model_response'].apply(extract_sentiment)
data_1['sentiment'].head()

0    Positive
1    Positive
2    Positive
3    Positive
4    Positive
Name: sentiment, dtype: object

In [38]:
data_1['sentiment'].value_counts()

sentiment
Positive    10
Negative     7
Neutral      3
Name: count, dtype: int64

In [39]:
final_data_1 = data_1.drop(['model_response'], axis=1)
final_data_1.head()

,restaurant_ID,rating_review,review_full,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive
4,EAT456,5,Had a great experience in the restaurant food ...,Positive

In [40]:
data_2 = data.copy()

In [41]:
# defining the instructions for the model
instruction_2 = """
    You are an AI analyzing restaurant reviews. Classify the sentiment of the provided review into the following categories:
    - Positive
    - Negative
    - Neutral

    Format the output as a JSON object with a single key-value pair as shown below:
    {"sentiment": "your_sentiment_prediction"}
"""

In [42]:
data_2['model_response'] = data_2['review_full'].apply(lambda x: generate_llama_response(instruction_2, x))

Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      97.73 ms /   161 runs   (    0.61 ms per token,  1647.43 tokens per second)
llama_print_timings: prompt eval time =     776.56 ms /   272 tokens (    2.85 ms per token,   350.26 tokens per second)
llama_print_timings:        eval time =   11650.38 ms /   160 runs   (   72.81 ms per token,    13.73 tokens per second)
llama_print_timings:       total time =   13174.38 ms /   432 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     135.53 ms /   225 runs   (    0.60 ms per token,  1660.17 tokens per second)
llama_print_timings: prompt eval time =     901.31 ms /   343 tokens (    2.63 ms per token,   380.56 tokens per second)
llama_print_timings:        eval time =   17006.37 ms /   224 runs   (   75.92 ms per token,    13.17 tokens per second)
llama_print_timings:       total time =   19066.65 ms /   567 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      26.91 ms /    48 runs   (    0.56 ms per token,  1783.72 tokens per second)
llama_print_timings: prompt eval time =     586.34 ms /   133 tokens (    4.41 ms per token,   226.83 tokens per second)
llama_print_timings:        eval time =    3515.98 ms /    47 runs   (   74.81 ms per token,    13.37 tokens per second)
llama_print_timings:       total time =    4288.76 ms /   180 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      70.23 ms /   109 runs   (    0.64 ms per token,  1552.15 tokens per second)
llama_print_timings: prompt eval time =     682.36 ms /   243 tokens (    2.81 ms per token,   356.12 tokens per second)
llama_print_timings:        eval time =    7812.35 ms /   108 runs   (   72.34 ms per token,    13.82 tokens per second)
llama_print_timings:       total time =    9024.70 ms /   351 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     140.05 ms /   238 runs   (    0.59 ms per token,  1699.39 tokens per second)
llama_print_timings: prompt eval time =     802.81 ms /   280 tokens (    2.87 ms per token,   348.78 tokens per second)
llama_print_timings:        eval time =   16625.73 ms /   237 runs   (   70.15 ms per token,    14.26 tokens per second)
llama_print_timings:       total time =   18507.70 ms /   517 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      83.22 ms /   130 runs   (    0.64 ms per token,  1562.14 tokens per second)
llama_print_timings: prompt eval time =     822.18 ms /   323 tokens (    2.55 ms per token,   392.86 tokens per second)
llama_print_timings:        eval time =    8857.58 ms /   129 runs   (   68.66 ms per token,    14.56 tokens per second)
llama_print_timings:       total time =   10301.44 ms /   452 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     158.01 ms /   259 runs   (    0.61 ms per token,  1639.11 tokens per second)
llama_print_timings: prompt eval time =     829.92 ms /   329 tokens (    2.52 ms per token,   396.42 tokens per second)
llama_print_timings:        eval time =   18288.21 ms /   258 runs   (   70.88 ms per token,    14.11 tokens per second)
llama_print_timings:       total time =   20389.53 ms /   587 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      50.33 ms /    90 runs   (    0.56 ms per token,  1788.06 tokens per second)
llama_print_timings: prompt eval time =     597.00 ms /   168 tokens (    3.55 ms per token,   281.41 tokens per second)
llama_print_timings:        eval time =    6563.71 ms /    89 runs   (   73.75 ms per token,    13.56 tokens per second)
llama_print_timings:       total time =    7523.18 ms /   257 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      89.23 ms /   140 runs   (    0.64 ms per token,  1569.03 tokens per second)
llama_print_timings: prompt eval time =     620.41 ms /   170 tokens (    3.65 ms per token,   274.01 tokens per second)
llama_print_timings:        eval time =   10075.93 ms /   139 runs   (   72.49 ms per token,    13.80 tokens per second)
llama_print_timings:       total time =   11364.17 ms /   309 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      47.49 ms /    78 runs   (    0.61 ms per token,  1642.45 tokens per second)
llama_print_timings: prompt eval time =     620.05 ms /   169 tokens (    3.67 ms per token,   272.56 tokens per second)
llama_print_timings:        eval time =    5551.87 ms /    77 runs   (   72.10 ms per token,    13.87 tokens per second)
llama_print_timings:       total time =    6538.48 ms /   246 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      74.43 ms /   134 runs   (    0.56 ms per token,  1800.33 tokens per second)
llama_print_timings: prompt eval time =     616.00 ms /   169 tokens (    3.64 ms per token,   274.35 tokens per second)
llama_print_timings:        eval time =    9654.82 ms /   133 runs   (   72.59 ms per token,    13.78 tokens per second)
llama_print_timings:       total time =   10836.19 ms /   302 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      50.42 ms /    80 runs   (    0.63 ms per token,  1586.77 tokens per second)
llama_print_timings: prompt eval time =     605.08 ms /   169 tokens (    3.58 ms per token,   279.30 tokens per second)
llama_print_timings:        eval time =    5474.47 ms /    79 runs   (   69.30 ms per token,    14.43 tokens per second)
llama_print_timings:       total time =    6485.93 ms /   248 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      43.82 ms /    78 runs   (    0.56 ms per token,  1779.89 tokens per second)
llama_print_timings: prompt eval time =     603.00 ms /   165 tokens (    3.65 ms per token,   273.63 tokens per second)
llama_print_timings:        eval time =    5452.03 ms /    77 runs   (   70.81 ms per token,    14.12 tokens per second)
llama_print_timings:       total time =    6365.54 ms /   242 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      80.99 ms /   127 runs   (    0.64 ms per token,  1568.04 tokens per second)
llama_print_timings: prompt eval time =    1025.29 ms /   471 tokens (    2.18 ms per token,   459.38 tokens per second)
llama_print_timings:        eval time =    8989.69 ms /   126 runs   (   71.35 ms per token,    14.02 tokens per second)
llama_print_timings:       total time =   10620.20 ms /   597 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      73.90 ms /   115 runs   (    0.64 ms per token,  1556.20 tokens per second)
llama_print_timings: prompt eval time =    1687.61 ms /   642 tokens (    2.63 ms per token,   380.42 tokens per second)
llama_print_timings:        eval time =    8244.09 ms /   114 runs   (   72.32 ms per token,    13.83 tokens per second)
llama_print_timings:       total time =   10517.39 ms /   756 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     114.19 ms /   172 runs   (    0.66 ms per token,  1506.27 tokens per second)
llama_print_timings: prompt eval time =     927.98 ms /   383 tokens (    2.42 ms per token,   412.72 tokens per second)
llama_print_timings:        eval time =   12230.81 ms /   171 runs   (   71.53 ms per token,    13.98 tokens per second)
llama_print_timings:       total time =   13994.92 ms /   554 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      74.43 ms /   118 runs   (    0.63 ms per token,  1585.47 tokens per second)
llama_print_timings: prompt eval time =     947.60 ms /   387 tokens (    2.45 ms per token,   408.40 tokens per second)
llama_print_timings:        eval time =    8361.03 ms /   117 runs   (   71.46 ms per token,    13.99 tokens per second)
llama_print_timings:       total time =    9882.73 ms /   504 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     111.31 ms /   172 runs   (    0.65 ms per token,  1545.18 tokens per second)
llama_print_timings: prompt eval time =    1012.74 ms /   451 tokens (    2.25 ms per token,   445.33 tokens per second)
llama_print_timings:        eval time =   12394.94 ms /   171 runs   (   72.49 ms per token,    13.80 tokens per second)
llama_print_timings:       total time =   14239.79 ms /   622 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      91.00 ms /   155 runs   (    0.59 ms per token,  1703.32 tokens per second)
llama_print_timings: prompt eval time =    1569.46 ms /   581 tokens (    2.70 ms per token,   370.19 tokens per second)
llama_print_timings:        eval time =   11378.74 ms /   154 runs   (   73.89 ms per token,    13.53 tokens per second)
llama_print_timings:       total time =   13674.35 ms /   735 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     159.09 ms /   250 runs   (    0.64 ms per token,  1571.41 tokens per second)
llama_print_timings: prompt eval time =     972.94 ms /   404 tokens (    2.41 ms per token,   415.24 tokens per second)
llama_print_timings:        eval time =   18132.16 ms /   249 runs   (   72.82 ms per token,    13.73 tokens per second)
llama_print_timings:       total time =   20329.05 ms /   653 tokens

In [43]:
data_2['model_response'].head()

0     Sure! Here's the sentiment analysis of the re...
1     Sure! Here's my analysis of the review you pr...
2     Sure, I can help you with that! Based on the ...
3     Sure! Here's the sentiment analysis of the re...
4     Sure! Here's the sentiment analysis of the re...
Name: model_response, dtype: object

In [44]:
i = 2
print(data_2.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [45]:
print(data_2.loc[i, 'model_response'])

 Sure, I can help you with that! Based on the review you provided, I would classify the sentiment as Positive. Here's the JSON object with the sentiment prediction:

{"sentiment": "Positive"}

In [46]:
# applying the function to the model response
data_2['model_response_parsed'] = data_2['model_response'].apply(extract_json_data)
data_2['model_response_parsed'].head()

0    {'sentiment': 'Positive'}
1    {'sentiment': 'Positive'}
2    {'sentiment': 'Positive'}
3    {'sentiment': 'Positive'}
4    {'sentiment': 'Positive'}
Name: model_response_parsed, dtype: object

In [47]:
model_response_parsed_df_2 = pd.json_normalize(data_2['model_response_parsed'])
model_response_parsed_df_2.head()

  sentiment
0  Positive
1  Positive
2  Positive
3  Positive
4  Positive

In [48]:
data_with_parsed_model_output_2 = pd.concat([data_2, model_response_parsed_df_2], axis=1)
data_with_parsed_model_output_2.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...",Sure! Here's the sentiment analysis of the re...,{'sentiment': 'Positive'},Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Sure! Here's my analysis of the review you pr...,{'sentiment': 'Positive'},Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"Sure, I can help you with that! Based on the ...",{'sentiment': 'Positive'},Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Sure! Here's the sentiment analysis of the re...,{'sentiment': 'Positive'},Positive
4,EAT456,5,Had a great experience in the restaurant food ...,Sure! Here's the sentiment analysis of the re...,{'sentiment': 'Positive'},Positive

In [49]:
final_data_2 = data_with_parsed_model_output_2.drop(['model_response','model_response_parsed'], axis=1)
final_data_2.head()

,restaurant_ID,rating_review,review_full,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive
4,EAT456,5,Had a great experience in the restaurant food ...,Positive

In [50]:
final_data_2['sentiment'].value_counts()

sentiment
Neutral     7
Negative    7
Positive    6
Name: count, dtype: int64

In [51]:
data_3 = data.copy()

In [52]:
# defining the instructions for the model
instruction_3 = """
    You are an AI analyzing restaurant reviews. Classify the overall sentiment of the provided review into the following categories:
    - "Positive"
    - "Negative"
    - "Neutral"

    Once that is done, check for a mention of the following aspects in the review and classify the sentiment of each aspect as "Positive", "Negative", or "Neutral":
    1. "Food Quality"
    2. "Service"
    3. "Ambience"

    Output the overall sentiment and sentiment for each category in a JSON format with the following keys:
    {
        "Overall": "your_sentiment_prediction",
        "Food Quality": "your_sentiment_prediction",
        "Service": "your_sentiment_prediction",
        "Ambience": "your_sentiment_prediction"
    }

    In case one of the three aspects is not mentioned in the review, set "Not Applicable" (including quotes) for the corresponding JSON key value.
    Only return the JSON, do not return any other information.
"""

In [53]:
data_3['model_response'] = data_3['review_full'].apply(lambda x: generate_llama_response(instruction_3, x))

Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     628.48 ms /  1024 runs   (    0.61 ms per token,  1629.32 tokens per second)
llama_print_timings: prompt eval time =     966.95 ms /   451 tokens (    2.14 ms per token,   466.42 tokens per second)
llama_print_timings:        eval time =   75713.59 ms /  1023 runs   (   74.01 ms per token,    13.51 tokens per second)
llama_print_timings:       total time =   82509.20 ms /  1474 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     111.81 ms /   190 runs   (    0.59 ms per token,  1699.33 tokens per second)
llama_print_timings: prompt eval time =    1417.80 ms /   522 tokens (    2.72 ms per token,   368.18 tokens per second)
llama_print_timings:        eval time =   13829.42 ms /   189 runs   (   73.17 ms per token,    13.67 tokens per second)
llama_print_timings:       total time =   16135.62 ms /   711 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      26.64 ms /    47 runs   (    0.57 ms per token,  1764.46 tokens per second)
llama_print_timings: prompt eval time =     855.38 ms /   312 tokens (    2.74 ms per token,   364.75 tokens per second)
llama_print_timings:        eval time =    3398.15 ms /    46 runs   (   73.87 ms per token,    13.54 tokens per second)
llama_print_timings:       total time =    4443.88 ms /   358 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      31.19 ms /    47 runs   (    0.66 ms per token,  1507.09 tokens per second)
llama_print_timings: prompt eval time =    1000.26 ms /   422 tokens (    2.37 ms per token,   421.89 tokens per second)
llama_print_timings:        eval time =    3341.65 ms /    46 runs   (   72.64 ms per token,    13.77 tokens per second)
llama_print_timings:       total time =    4592.61 ms /   468 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     606.73 ms /  1024 runs   (    0.59 ms per token,  1687.74 tokens per second)
llama_print_timings: prompt eval time =    1033.39 ms /   459 tokens (    2.25 ms per token,   444.17 tokens per second)
llama_print_timings:        eval time =   76635.33 ms /  1023 runs   (   74.91 ms per token,    13.35 tokens per second)
llama_print_timings:       total time =   83063.10 ms /  1482 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      28.82 ms /    49 runs   (    0.59 ms per token,  1700.44 tokens per second)
llama_print_timings: prompt eval time =    1078.63 ms /   502 tokens (    2.15 ms per token,   465.41 tokens per second)
llama_print_timings:        eval time =    3531.55 ms /    48 runs   (   73.57 ms per token,    13.59 tokens per second)
llama_print_timings:       total time =    4803.23 ms /   550 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     631.82 ms /  1024 runs   (    0.62 ms per token,  1620.73 tokens per second)
llama_print_timings: prompt eval time =    1084.07 ms /   508 tokens (    2.13 ms per token,   468.61 tokens per second)
llama_print_timings:        eval time =   76407.99 ms /  1023 runs   (   74.69 ms per token,    13.39 tokens per second)
llama_print_timings:       total time =   83129.47 ms /  1531 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      29.11 ms /    52 runs   (    0.56 ms per token,  1786.08 tokens per second)
llama_print_timings: prompt eval time =     865.63 ms /   347 tokens (    2.49 ms per token,   400.87 tokens per second)
llama_print_timings:        eval time =    3727.50 ms /    51 runs   (   73.09 ms per token,    13.68 tokens per second)
llama_print_timings:       total time =    4802.22 ms /   398 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      28.02 ms /    51 runs   (    0.55 ms per token,  1820.26 tokens per second)
llama_print_timings: prompt eval time =     868.69 ms /   349 tokens (    2.49 ms per token,   401.75 tokens per second)
llama_print_timings:        eval time =    3674.38 ms /    50 runs   (   73.49 ms per token,    13.61 tokens per second)
llama_print_timings:       total time =    4733.17 ms /   399 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      34.01 ms /    52 runs   (    0.65 ms per token,  1528.92 tokens per second)
llama_print_timings: prompt eval time =     869.18 ms /   348 tokens (    2.50 ms per token,   400.38 tokens per second)
llama_print_timings:        eval time =    3633.51 ms /    51 runs   (   71.25 ms per token,    14.04 tokens per second)
llama_print_timings:       total time =    4766.58 ms /   399 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      28.16 ms /    52 runs   (    0.54 ms per token,  1846.46 tokens per second)
llama_print_timings: prompt eval time =     867.04 ms /   348 tokens (    2.49 ms per token,   401.37 tokens per second)
llama_print_timings:        eval time =    3746.15 ms /    51 runs   (   73.45 ms per token,    13.61 tokens per second)
llama_print_timings:       total time =    4806.06 ms /   399 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      32.20 ms /    52 runs   (    0.62 ms per token,  1614.86 tokens per second)
llama_print_timings: prompt eval time =     877.18 ms /   348 tokens (    2.52 ms per token,   396.73 tokens per second)
llama_print_timings:        eval time =    3698.01 ms /    51 runs   (   72.51 ms per token,    13.79 tokens per second)
llama_print_timings:       total time =    4811.08 ms /   399 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      31.31 ms /    51 runs   (    0.61 ms per token,  1628.92 tokens per second)
llama_print_timings: prompt eval time =     857.56 ms /   344 tokens (    2.49 ms per token,   401.14 tokens per second)
llama_print_timings:        eval time =    3621.30 ms /    50 runs   (   72.43 ms per token,    13.81 tokens per second)
llama_print_timings:       total time =    4710.12 ms /   394 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      29.60 ms /    52 runs   (    0.57 ms per token,  1756.76 tokens per second)
llama_print_timings: prompt eval time =    1719.08 ms /   650 tokens (    2.64 ms per token,   378.11 tokens per second)
llama_print_timings:        eval time =    3843.92 ms /    51 runs   (   75.37 ms per token,    13.27 tokens per second)
llama_print_timings:       total time =    5765.10 ms /   701 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     629.54 ms /  1024 runs   (    0.61 ms per token,  1626.59 tokens per second)
llama_print_timings: prompt eval time =    1988.01 ms /   821 tokens (    2.42 ms per token,   412.98 tokens per second)
llama_print_timings:        eval time =   76883.39 ms /  1023 runs   (   75.15 ms per token,    13.31 tokens per second)
llama_print_timings:       total time =   84689.34 ms /  1844 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      31.00 ms /    52 runs   (    0.60 ms per token,  1677.64 tokens per second)
llama_print_timings: prompt eval time =    1496.89 ms /   562 tokens (    2.66 ms per token,   375.45 tokens per second)
llama_print_timings:        eval time =    3732.82 ms /    51 runs   (   73.19 ms per token,    13.66 tokens per second)
llama_print_timings:       total time =    5450.89 ms /   613 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      36.72 ms /    53 runs   (    0.69 ms per token,  1443.51 tokens per second)
llama_print_timings: prompt eval time =    1514.90 ms /   566 tokens (    2.68 ms per token,   373.62 tokens per second)
llama_print_timings:        eval time =    3709.17 ms /    52 runs   (   71.33 ms per token,    14.02 tokens per second)
llama_print_timings:       total time =    5535.43 ms /   618 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     188.23 ms /   294 runs   (    0.64 ms per token,  1561.89 tokens per second)
llama_print_timings: prompt eval time =    1613.21 ms /   630 tokens (    2.56 ms per token,   390.52 tokens per second)
llama_print_timings:        eval time =   21747.20 ms /   293 runs   (   74.22 ms per token,    13.47 tokens per second)
llama_print_timings:       total time =   24810.34 ms /   923 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      28.77 ms /    51 runs   (    0.56 ms per token,  1772.68 tokens per second)
llama_print_timings: prompt eval time =    1787.83 ms /   760 tokens (    2.35 ms per token,   425.10 tokens per second)
llama_print_timings:        eval time =    3709.86 ms /    50 runs   (   74.20 ms per token,    13.48 tokens per second)
llama_print_timings:       total time =    5715.14 ms /   810 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      29.88 ms /    51 runs   (    0.59 ms per token,  1706.71 tokens per second)
llama_print_timings: prompt eval time =    1563.29 ms /   583 tokens (    2.68 ms per token,   372.93 tokens per second)
llama_print_timings:        eval time =    3718.84 ms /    50 runs   (   74.38 ms per token,    13.45 tokens per second)
llama_print_timings:       total time =    5494.10 ms /   633 tokens

In [54]:
data_3['model_response'].head()

0    \n    {\n        "Overall": "Positive",\n     ...
1    \n    {\n        "Overall": "Positive",\n     ...
2     {\n            "Overall": "Positive",\n      ...
3     {\n        "Overall": "Positive",\n        "F...
4    \n    {\n        "Overall": "Positive",\n     ...
Name: model_response, dtype: object

In [55]:
i = 2
print(data_3.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [56]:
print(data_3.loc[i, 'model_response'])

 {
            "Overall": "Positive",
            "Food Quality": "Positive",
            "Service": "Positive",
            "Ambience": "Positive"
          }

In [57]:

data_3['model_response_parsed'] = data_3['model_response'].apply(extract_json_data)
data_3['model_response_parsed'].head()

0    {'Overall': 'Positive', 'Food Quality': 'Posit...
1    {'Overall': 'Positive', 'Food Quality': 'Posit...
2    {'Overall': 'Positive', 'Food Quality': 'Posit...
3    {'Overall': 'Positive', 'Food Quality': 'Posit...
4    {'Overall': 'Positive', 'Food Quality': 'Posit...
Name: model_response_parsed, dtype: object

In [58]:
model_response_parsed_df_3 = pd.json_normalize(data_3['model_response_parsed'])
model_response_parsed_df_3.head()

    Overall Food Quality   Service  Ambience
0  Positive     Positive  Positive  Positive
1  Positive     Positive   Neutral  Positive
2  Positive     Positive  Positive  Positive
3  Positive     Positive  Positive  Positive
4  Positive     Positive  Positive  Positive

In [59]:
data_with_parsed_model_output_3 = pd.concat([data_3, model_response_parsed_df_3], axis=1)
data_with_parsed_model_output_3.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...","\n {\n ""Overall"": ""Positive"",\n ...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,"\n {\n ""Overall"": ""Positive"",\n ...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Neutral,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{\n ""Overall"": ""Positive"",\n ...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,"{\n ""Overall"": ""Positive"",\n ""F...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive
4,EAT456,5,Had a great experience in the restaurant food ...,"\n {\n ""Overall"": ""Positive"",\n ...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive

In [60]:
final_data_3 = data_with_parsed_model_output_3.drop(['model_response','model_response_parsed'], axis=1)
final_data_3.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive,Positive,Positive,Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive,Positive,Neutral,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive,Positive,Positive,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive,Positive,Positive,Positive
4,EAT456,5,Had a great experience in the restaurant food ...,Positive,Positive,Positive,Positive

In [61]:
final_data_3['Overall'].value_counts()

Overall
Neutral     7
Negative    7
Positive    6
Name: count, dtype: int64

In [62]:
final_data_3['Food Quality'].value_counts()

Food Quality
Positive          7
Neutral           7
Negative          3
Mixed             2
Not Applicable    1
Name: count, dtype: int64

In [63]:
final_data_3['Service'].value_counts()

Service
Negative        9
Positive        8
Neutral         1
Slow            1
Inconsistent    1
Name: count, dtype: int64

In [64]:
final_data_3['Ambience'].value_counts()

Ambience
Positive          9
Not Applicable    6
Neutral           4
Negative          1
Name: count, dtype: int64

In [65]:
data_3 = data.copy()

In [70]:
def response_2(prompt,review,sentiment):
    model_output = mistral_llm(
      f"""
      Q: {prompt}
      review: {review}
      sentiment: {sentiment}
      A:
      """,
      max_tokens=64,
      stop=["Q:", "\n"],
      temperature=0.01,
      echo=False,
    )

    temp_output = model_output["choices"][0]["text"]
    final_output = temp_output[temp_output.index('{'):]

    return final_output

In [67]:

instruction_3 = """
    You are provided a review and it's sentiment.

    Instructions:
    Classify the sentiment of each aspect as either of "Positive", "Negative", or "Neutral" only and not any other for the given review:
    1. "Food Quality"
    2. "Service"
    3. "Ambience"
    In case one of the three aspects is not mentioned in the review, return "Not Applicable" (including quotes) for the corresponding JSON key value.
    Return the output in the format {"Overall": given sentiment input,"Food Quality": "your_sentiment_prediction","Service": "your_sentiment_prediction","Ambience": "your_sentiment_prediction"}

"""

In [71]:
data_3['model_response'] = final_data_1[['review_full','sentiment']].apply(lambda x: response_2(instruction_3, x[0],x[1]),axis=1)

/tmp/ipython-input-399174068.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_3['model_response'] = final_data_1[['review_full','sentiment']].apply(lambda x: response_2(instruction_3, x[0],x[1]),axis=1)
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.89 ms /    31 runs   (    0.58 ms per token,  1732.81 tokens per second)
llama_print_timings: prompt eval time =    4178.86 ms /   341 tokens (   12.25 ms per token,    81.60 tokens per second)
llama_print_timings:        eval time =   26694.98 ms /    30 runs   (  889.83 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   31014.43 ms /   371 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.68 ms /    33 runs   (    0.57 ms per token,  1766.60 tokens per second)
llama_print_timings: prompt eval time =    2872.92 ms /   241 tokens (   11.92 ms per token,    83.89 tokens per second)
llama_print_timings:        eval time =   28458.35 ms /    32 runs   (  889.32 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   31493.74 ms /   273 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.94 ms /    31 runs   (    0.58 ms per token,  1728.37 tokens per second)
llama_print_timings: prompt eval time =    1673.16 ms /    40 tokens (   41.83 ms per token,    23.91 tokens per second)
llama_print_timings:        eval time =   26642.71 ms /    30 runs   (  888.09 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   28451.25 ms /    70 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      19.96 ms /    35 runs   (    0.57 ms per token,  1753.95 tokens per second)
llama_print_timings: prompt eval time =    2266.42 ms /   149 tokens (   15.21 ms per token,    65.74 tokens per second)
llama_print_timings:        eval time =   30320.29 ms /    34 runs   (  891.77 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   32742.34 ms /   183 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.02 ms /    31 runs   (    0.58 ms per token,  1720.79 tokens per second)
llama_print_timings: prompt eval time =    2868.70 ms /   175 tokens (   16.39 ms per token,    61.00 tokens per second)
llama_print_timings:        eval time =   26686.97 ms /    30 runs   (  889.57 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   29696.45 ms /   205 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.93 ms /    31 runs   (    0.58 ms per token,  1729.43 tokens per second)
llama_print_timings: prompt eval time =    2750.32 ms /   223 tokens (   12.33 ms per token,    81.08 tokens per second)
llama_print_timings:        eval time =   26699.43 ms /    30 runs   (  889.98 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   29590.14 ms /   253 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      19.36 ms /    32 runs   (    0.61 ms per token,  1652.72 tokens per second)
llama_print_timings: prompt eval time =    2672.51 ms /   221 tokens (   12.09 ms per token,    82.69 tokens per second)
llama_print_timings:        eval time =   27535.78 ms /    31 runs   (  888.25 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   30348.20 ms /   252 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      19.22 ms /    34 runs   (    0.57 ms per token,  1768.81 tokens per second)
llama_print_timings: prompt eval time =    1843.47 ms /    75 tokens (   24.58 ms per token,    40.68 tokens per second)
llama_print_timings:        eval time =   29036.19 ms /    33 runs   (  879.88 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   31029.02 ms /   108 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.21 ms /    32 runs   (    0.57 ms per token,  1757.18 tokens per second)
llama_print_timings: prompt eval time =    1921.18 ms /    73 tokens (   26.32 ms per token,    38.00 tokens per second)
llama_print_timings:        eval time =   27406.88 ms /    31 runs   (  884.09 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   29466.87 ms /   104 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      19.36 ms /    35 runs   (    0.55 ms per token,  1807.66 tokens per second)
llama_print_timings: prompt eval time =    2062.48 ms /    75 tokens (   27.50 ms per token,    36.36 tokens per second)
llama_print_timings:        eval time =   29763.03 ms /    34 runs   (  875.38 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   31979.15 ms /   109 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.28 ms /    33 runs   (    0.55 ms per token,  1805.45 tokens per second)
llama_print_timings: prompt eval time =    1808.60 ms /    72 tokens (   25.12 ms per token,    39.81 tokens per second)
llama_print_timings:        eval time =   27958.65 ms /    32 runs   (  873.71 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   29904.86 ms /   104 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.83 ms /    32 runs   (    0.59 ms per token,  1699.42 tokens per second)
llama_print_timings: prompt eval time =    1830.26 ms /    77 tokens (   23.77 ms per token,    42.07 tokens per second)
llama_print_timings:        eval time =   26911.81 ms /    31 runs   (  868.12 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   28878.65 ms /   108 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.61 ms /    32 runs   (    0.55 ms per token,  1817.36 tokens per second)
llama_print_timings: prompt eval time =    1798.85 ms /    71 tokens (   25.34 ms per token,    39.47 tokens per second)
llama_print_timings:        eval time =   27035.42 ms /    31 runs   (  872.11 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   28969.23 ms /   102 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      20.30 ms /    34 runs   (    0.60 ms per token,  1675.04 tokens per second)
llama_print_timings: prompt eval time =    4230.35 ms /   360 tokens (   11.75 ms per token,    85.10 tokens per second)
llama_print_timings:        eval time =   29206.28 ms /    33 runs   (  885.04 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   33587.95 ms /   393 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      20.10 ms /    33 runs   (    0.61 ms per token,  1641.87 tokens per second)
llama_print_timings: prompt eval time =   17096.18 ms /   532 tokens (   32.14 ms per token,    31.12 tokens per second)
llama_print_timings:        eval time =   28231.64 ms /    32 runs   (  882.24 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   45484.02 ms /   564 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      19.31 ms /    34 runs   (    0.57 ms per token,  1760.56 tokens per second)
llama_print_timings: prompt eval time =    3130.97 ms /   280 tokens (   11.18 ms per token,    89.43 tokens per second)
llama_print_timings:        eval time =   29681.23 ms /    33 runs   (  899.43 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   32967.07 ms /   313 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.76 ms /    33 runs   (    0.57 ms per token,  1759.34 tokens per second)
llama_print_timings: prompt eval time =    3497.48 ms /   290 tokens (   12.06 ms per token,    82.92 tokens per second)
llama_print_timings:        eval time =   28166.12 ms /    32 runs   (  880.19 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   31811.37 ms /   322 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.68 ms /    33 runs   (    0.57 ms per token,  1766.60 tokens per second)
llama_print_timings: prompt eval time =    3609.45 ms /   341 tokens (   10.58 ms per token,    94.47 tokens per second)
llama_print_timings:        eval time =   28253.79 ms /    32 runs   (  882.93 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   32010.48 ms /   373 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      17.51 ms /    31 runs   (    0.56 ms per token,  1770.21 tokens per second)
llama_print_timings: prompt eval time =    5455.68 ms /   468 tokens (   11.66 ms per token,    85.78 tokens per second)
llama_print_timings:        eval time =   26652.21 ms /    30 runs   (  888.41 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   32252.21 ms /   498 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3066.92 ms
llama_print_timings:      sample time =      18.06 ms /    32 runs   (    0.56 ms per token,  1772.26 tokens per second)
llama_print_timings: prompt eval time =    3334.29 ms /   303 tokens (   11.00 ms per token,    90.87 tokens per second)
llama_print_timings:        eval time =   27257.59 ms /    31 runs   (  879.28 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   30732.19 ms /   334 tokens

In [72]:
data_3['model_response'].values

array(['{"Overall": "Positive","Food Quality": "Positive","Service": "Positive","Ambience": "Positive"}',
       '{"Overall": "Positive","Food Quality": "Positive","Service": "Not Applicable","Ambience": "Positive"}',
       '{"Overall": "Positive","Food Quality": "Positive","Service": "Positive","Ambience": "Positive"}',
       '{"Overall": "Positive","Food Quality": "Not Applicable","Service": "Positive","Ambience": "Not Applicable"}',
       '{"Overall": "Positive","Food Quality": "Positive","Service": "Positive","Ambience": "Positive"}',
       '{"Overall": "Positive","Food Quality": "Positive","Service": "Positive","Ambience": "Positive"}',
       '{"Overall": "Positive","Food Quality": "Neutral","Service": "Positive","Ambience": "Positive"}',
       '{"Overall": "Positive","Food Quality": "Neutral","Service": "Negative","Ambience": "Not Applicable"}',
       '{"Overall": "Positive","Food Quality": "Neutral","Service": "Negative","Ambience": "Positive"}',
       '{"Overall": "Neutral","Food Quality": "If not exceptional","Service": "Positive","Ambience": "Not Applicable"}',
       '{"Overall": "Neutral","Food Quality": "Decent","Service": "Prompt","Ambience": "Neutral"}',
       '{"Overall": "Positive","Food Quality": "Neutral","Service": "Negative","Ambience": "Positive"}',
       '{"Overall": "Neutral","Food Quality": "Negative","Service": "Positive","Ambience": "Positive"}',
       '{"Overall": "Negative","Food Quality": "Not Applicable","Service": "Negative","Ambience": "Neutral"}',
       '{"Overall": "Negative","Food Quality": "Negative","Service": "Negative","Ambience": "Not Applicable"}',
       '{"Overall": "Negative","Food Quality": "Neutral","Service": "Negative","Ambience": "Not Applicable"}',
       '{"Overall": "Negative","Food Quality": "Not Applicable","Service": "Negative","Ambience": "Negative"}',
       '{"Overall": "Negative","Food Quality": "Not Applicable","Service": "Negative","Ambience": "Negative"}',
       '{"Overall": "Negative","Food Quality": "Negative","Service": "Negative","Ambience": "Negative"}',
       '{"Overall": "Negative","Food Quality": "Positive","Service": "Negative","Ambience": "Neutral"}'],
      dtype=object)

In [73]:
i = 2
print(data_3.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [74]:
print(data_3.loc[i, 'model_response'])

{"Overall": "Positive","Food Quality": "Positive","Service": "Positive","Ambience": "Positive"}

In [75]:

data_3['model_response_parsed'] = data_3['model_response'].apply(extract_json_data)
data_3['model_response_parsed']

0     {'Overall': 'Positive', 'Food Quality': 'Posit...
1     {'Overall': 'Positive', 'Food Quality': 'Posit...
2     {'Overall': 'Positive', 'Food Quality': 'Posit...
3     {'Overall': 'Positive', 'Food Quality': 'Not A...
4     {'Overall': 'Positive', 'Food Quality': 'Posit...
5     {'Overall': 'Positive', 'Food Quality': 'Posit...
6     {'Overall': 'Positive', 'Food Quality': 'Neutr...
7     {'Overall': 'Positive', 'Food Quality': 'Neutr...
8     {'Overall': 'Positive', 'Food Quality': 'Neutr...
9     {'Overall': 'Neutral', 'Food Quality': 'If not...
10    {'Overall': 'Neutral', 'Food Quality': 'Decent...
11    {'Overall': 'Positive', 'Food Quality': 'Neutr...
12    {'Overall': 'Neutral', 'Food Quality': 'Negati...
13    {'Overall': 'Negative', 'Food Quality': 'Not A...
14    {'Overall': 'Negative', 'Food Quality': 'Negat...
15    {'Overall': 'Negative', 'Food Quality': 'Neutr...
16    {'Overall': 'Negative', 'Food Quality': 'Not A...
17    {'Overall': 'Negative', 'Food Quality': 'Not A...
18    {'Overall': 'Negative', 'Food Quality': 'Negat...
19    {'Overall': 'Negative', 'Food Quality': 'Posit...
Name: model_response_parsed, dtype: object

In [76]:
model_response_parsed_df_3 = pd.json_normalize(data_3['model_response_parsed'])
model_response_parsed_df_3

     Overall        Food Quality         Service        Ambience
0   Positive            Positive        Positive        Positive
1   Positive            Positive  Not Applicable        Positive
2   Positive            Positive        Positive        Positive
3   Positive      Not Applicable        Positive  Not Applicable
4   Positive            Positive        Positive        Positive
5   Positive            Positive        Positive        Positive
6   Positive             Neutral        Positive        Positive
7   Positive             Neutral        Negative  Not Applicable
8   Positive             Neutral        Negative        Positive
9    Neutral  If not exceptional        Positive  Not Applicable
10   Neutral              Decent          Prompt         Neutral
11  Positive             Neutral        Negative        Positive
12   Neutral            Negative        Positive        Positive
13  Negative      Not Applicable        Negative         Neutral
14  Negative            Negative        Negative  Not Applicable
15  Negative             Neutral        Negative  Not Applicable
16  Negative      Not Applicable        Negative        Negative
17  Negative      Not Applicable        Negative        Negative
18  Negative            Negative        Negative        Negative
19  Negative            Positive        Negative         Neutral

In [77]:
model_response_parsed_df_3 = model_response_parsed_df_3.apply(lambda x: x.astype(str).str.lower())

In [78]:
data_with_parsed_model_output_3 = pd.concat([data_3, model_response_parsed_df_3], axis=1)
data_with_parsed_model_output_3.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...","{""Overall"": ""Positive"",""Food Quality"": ""Positi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,positive,positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,"{""Overall"": ""Positive"",""Food Quality"": ""Positi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,not applicable,positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{""Overall"": ""Positive"",""Food Quality"": ""Positi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,positive,positive
3,TST101,5,I have visited at jw lough/restourant. There w...,"{""Overall"": ""Positive"",""Food Quality"": ""Not Ap...","{'Overall': 'Positive', 'Food Quality': 'Not A...",positive,not applicable,positive,not applicable
4,EAT456,5,Had a great experience in the restaurant food ...,"{""Overall"": ""Positive"",""Food Quality"": ""Positi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,positive,positive

In [79]:
final_data_3 = data_with_parsed_model_output_3.drop(['model_response','model_response_parsed'], axis=1)
final_data_3.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...",positive,positive,positive,positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,positive,positive,not applicable,positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,positive,positive,positive,positive
3,TST101,5,I have visited at jw lough/restourant. There w...,positive,not applicable,positive,not applicable
4,EAT456,5,Had a great experience in the restaurant food ...,positive,positive,positive,positive

In [80]:
final_data_3['Overall'].value_counts()

Overall
positive    10
negative     7
neutral      3
Name: count, dtype: int64

In [81]:
final_data_3['Food Quality'].value_counts()

Food Quality
positive              6
neutral               5
not applicable        4
negative              3
if not exceptional    1
decent                1
Name: count, dtype: int64

In [82]:
final_data_3['Service'].value_counts()

Service
negative          10
positive           8
not applicable     1
prompt             1
Name: count, dtype: int64

In [83]:
final_data_3['Ambience'].value_counts()

Ambience
positive          9
not applicable    5
neutral           3
negative          3
Name: count, dtype: int64

In [84]:
data_4 = data.copy()

In [85]:

instruction_4 = """
    You are an AI tasked with analyzing restaurant reviews. Your goal is to classify the overall sentiment of the provided review into the following categories:
        - Positive
        - Negative
        - Neutral

    Subsequently, assess the sentiment of specific aspects mentioned in the review, namely:
        1. Food quality
        2. Service
        3. Ambience

    Further, identify liked and/or disliked features associated with each aspect in the review.

    Return the output in the specified JSON format, ensuring consistency and handling missing values appropriately:

    {
        "Overall": "your_sentiment_prediction",
        "Food Quality": "your_sentiment_prediction",
        "Service": "your_sentiment_prediction",
        "Ambience": "your_sentiment_prediction",
        "Food Quality Features": ["liked/disliked features"],
        "Service Features": ["liked/disliked features"],
        "Ambience Features": ["liked/disliked features"]
    }

    The sentiment prediction for Overall, Food Quality, Service, and Ambience should be one of "Positive", "Negative", or "Neutral" only.
    In case one of the three aspects is not mentioned in the review, set "Not Applicable" (including quotes) in the corresponding JSON key value for the sentiment.
    In case there are no liked/disliked features for a particular aspect, assign an empty list in the corresponding JSON key value for the aspect.
    Only return the JSON, do NOT return any other text or information.
"""

In [86]:
data_4['model_response'] = data_4['review_full'].apply(lambda x: generate_llama_response(instruction_4, x).replace('\n', ''))

Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     177.78 ms /   294 runs   (    0.60 ms per token,  1653.74 tokens per second)
llama_print_timings: prompt eval time =    1503.41 ms /   574 tokens (    2.62 ms per token,   381.80 tokens per second)
llama_print_timings:        eval time =   21922.96 ms /   293 runs   (   74.82 ms per token,    13.36 tokens per second)
llama_print_timings:       total time =   24851.32 ms /   867 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     151.19 ms /   246 runs   (    0.61 ms per token,  1627.11 tokens per second)
llama_print_timings: prompt eval time =    1806.78 ms /   645 tokens (    2.80 ms per token,   356.99 tokens per second)
llama_print_timings:        eval time =   18595.54 ms /   245 runs   (   75.90 ms per token,    13.18 tokens per second)
llama_print_timings:       total time =   21640.54 ms /   890 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     174.55 ms /   281 runs   (    0.62 ms per token,  1609.87 tokens per second)
llama_print_timings: prompt eval time =     997.76 ms /   435 tokens (    2.29 ms per token,   435.97 tokens per second)
llama_print_timings:        eval time =   19759.57 ms /   280 runs   (   70.57 ms per token,    14.17 tokens per second)
llama_print_timings:       total time =   22094.58 ms /   715 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     206.02 ms /   345 runs   (    0.60 ms per token,  1674.60 tokens per second)
llama_print_timings: prompt eval time =    1445.34 ms /   545 tokens (    2.65 ms per token,   377.07 tokens per second)
llama_print_timings:        eval time =   25129.37 ms /   344 runs   (   73.05 ms per token,    13.69 tokens per second)
llama_print_timings:       total time =   28264.11 ms /   889 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     135.36 ms /   227 runs   (    0.60 ms per token,  1677.06 tokens per second)
llama_print_timings: prompt eval time =    1584.03 ms /   582 tokens (    2.72 ms per token,   367.42 tokens per second)
llama_print_timings:        eval time =   17208.65 ms /   226 runs   (   76.14 ms per token,    13.13 tokens per second)
llama_print_timings:       total time =   19857.98 ms /   808 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     174.08 ms /   274 runs   (    0.64 ms per token,  1574.02 tokens per second)
llama_print_timings: prompt eval time =    1622.62 ms /   625 tokens (    2.60 ms per token,   385.18 tokens per second)
llama_print_timings:        eval time =   20471.81 ms /   273 runs   (   74.99 ms per token,    13.34 tokens per second)
llama_print_timings:       total time =   23469.57 ms /   898 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     206.88 ms /   335 runs   (    0.62 ms per token,  1619.34 tokens per second)
llama_print_timings: prompt eval time =    1607.42 ms /   631 tokens (    2.55 ms per token,   392.55 tokens per second)
llama_print_timings:        eval time =   24586.66 ms /   334 runs   (   73.61 ms per token,    13.58 tokens per second)
llama_print_timings:       total time =   27870.28 ms /   965 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     168.15 ms /   274 runs   (    0.61 ms per token,  1629.52 tokens per second)
llama_print_timings: prompt eval time =    1029.15 ms /   470 tokens (    2.19 ms per token,   456.69 tokens per second)
llama_print_timings:        eval time =   20009.57 ms /   273 runs   (   73.30 ms per token,    13.64 tokens per second)
llama_print_timings:       total time =   22416.38 ms /   743 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     181.26 ms /   298 runs   (    0.61 ms per token,  1644.04 tokens per second)
llama_print_timings: prompt eval time =    1037.42 ms /   472 tokens (    2.20 ms per token,   454.98 tokens per second)
llama_print_timings:        eval time =   21868.89 ms /   297 runs   (   73.63 ms per token,    13.58 tokens per second)
llama_print_timings:       total time =   24382.41 ms /   769 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     225.66 ms /   383 runs   (    0.59 ms per token,  1697.28 tokens per second)
llama_print_timings: prompt eval time =    1030.13 ms /   471 tokens (    2.19 ms per token,   457.23 tokens per second)
llama_print_timings:        eval time =   27877.51 ms /   382 runs   (   72.98 ms per token,    13.70 tokens per second)
llama_print_timings:       total time =   30803.18 ms /   853 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     186.12 ms /   316 runs   (    0.59 ms per token,  1697.86 tokens per second)
llama_print_timings: prompt eval time =    1025.55 ms /   471 tokens (    2.18 ms per token,   459.26 tokens per second)
llama_print_timings:        eval time =   22737.67 ms /   315 runs   (   72.18 ms per token,    13.85 tokens per second)
llama_print_timings:       total time =   25324.73 ms /   786 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     161.17 ms /   269 runs   (    0.60 ms per token,  1669.07 tokens per second)
llama_print_timings: prompt eval time =    1027.03 ms /   471 tokens (    2.18 ms per token,   458.61 tokens per second)
llama_print_timings:        eval time =   19328.44 ms /   268 runs   (   72.12 ms per token,    13.87 tokens per second)
llama_print_timings:       total time =   21719.10 ms /   739 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     108.65 ms /   177 runs   (    0.61 ms per token,  1629.04 tokens per second)
llama_print_timings: prompt eval time =    1021.65 ms /   467 tokens (    2.19 ms per token,   457.10 tokens per second)
llama_print_timings:        eval time =   12721.46 ms /   176 runs   (   72.28 ms per token,    13.83 tokens per second)
llama_print_timings:       total time =   14598.84 ms /   643 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     200.04 ms /   316 runs   (    0.63 ms per token,  1579.68 tokens per second)
llama_print_timings: prompt eval time =    1931.01 ms /   773 tokens (    2.50 ms per token,   400.31 tokens per second)
llama_print_timings:        eval time =   23719.35 ms /   315 runs   (   75.30 ms per token,    13.28 tokens per second)
llama_print_timings:       total time =   27266.50 ms /  1088 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     220.30 ms /   355 runs   (    0.62 ms per token,  1611.48 tokens per second)
llama_print_timings: prompt eval time =    2152.83 ms /   944 tokens (    2.28 ms per token,   438.49 tokens per second)
llama_print_timings:        eval time =   26714.78 ms /   354 runs   (   75.47 ms per token,    13.25 tokens per second)
llama_print_timings:       total time =   30692.58 ms /  1298 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     264.17 ms /   388 runs   (    0.68 ms per token,  1468.78 tokens per second)
llama_print_timings: prompt eval time =    1733.68 ms /   685 tokens (    2.53 ms per token,   395.11 tokens per second)
llama_print_timings:        eval time =   28703.89 ms /   387 runs   (   74.17 ms per token,    13.48 tokens per second)
llama_print_timings:       total time =   32523.98 ms /  1072 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     127.56 ms /   215 runs   (    0.59 ms per token,  1685.55 tokens per second)
llama_print_timings: prompt eval time =    1750.95 ms /   689 tokens (    2.54 ms per token,   393.50 tokens per second)
llama_print_timings:        eval time =   16281.60 ms /   214 runs   (   76.08 ms per token,    13.14 tokens per second)
llama_print_timings:       total time =   19069.57 ms /   903 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     197.06 ms /   308 runs   (    0.64 ms per token,  1562.98 tokens per second)
llama_print_timings: prompt eval time =    1797.01 ms /   753 tokens (    2.39 ms per token,   419.03 tokens per second)
llama_print_timings:        eval time =   23024.51 ms /   307 runs   (   75.00 ms per token,    13.33 tokens per second)
llama_print_timings:       total time =   26415.89 ms /  1060 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     179.10 ms /   295 runs   (    0.61 ms per token,  1647.11 tokens per second)
llama_print_timings: prompt eval time =    2041.92 ms /   883 tokens (    2.31 ms per token,   432.44 tokens per second)
llama_print_timings:        eval time =   22172.31 ms /   294 runs   (   75.42 ms per token,    13.26 tokens per second)
llama_print_timings:       total time =   25742.29 ms /  1177 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     179.30 ms /   266 runs   (    0.67 ms per token,  1483.58 tokens per second)
llama_print_timings: prompt eval time =    1759.95 ms /   706 tokens (    2.49 ms per token,   401.15 tokens per second)
llama_print_timings:        eval time =   19445.68 ms /   265 runs   (   73.38 ms per token,    13.63 tokens per second)
llama_print_timings:       total time =   22629.21 ms /   971 tokens

In [87]:
i = 2
print(data_4.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [88]:
print(data_4.loc[i, 'model_response'])

 Sure, I can assist you in that! Here's my analysis of your provided review: {"Overall": "Positive", "Food Quality": "Positive", "Service": "Positive", "Ambience": "Positive", "Food Quality Features": ["Excellent taste"], "Service Features": ["Great service"], "Ambience Features": ["Awesome decorum"]} Based on the review, I have determined that: * The overall sentiment is positive, as mentioned in the review's opening sentence. * The food quality is also positive, as described as "Excellent taste." * The service is positive, as described as "Great." * The ambience is positive, as described as "Awesome decorum." * There were no mentioned liked/disliked features for any aspect, so I have assigned empty lists for those values. * I have set "Not Applicable" for the sentiment prediction for "Ambience" since it was not mentioned in the review. Please note that I have handled missing values appropriately by assigning appropriate values based on the context of the review.

In [89]:

data_4['model_response_parsed'] = data_4['model_response'].apply(extract_json_data)
data_4['model_response_parsed'].head()

0    {'Overall': 'Positive', 'Food Quality': 'Posit...
1    {'Overall': 'Positive', 'Food Quality': 'Posit...
2    {'Overall': 'Positive', 'Food Quality': 'Posit...
3    {'Overall': 'Positive', 'Food Quality': 'Posit...
4    {'Overall': 'Positive', 'Food Quality': 'Posit...
Name: model_response_parsed, dtype: object

In [90]:
data_4[data_4.model_response_parsed == {}]

Empty DataFrame
Columns: [restaurant_ID, rating_review, review_full, model_response, model_response_parsed]
Index: []

In [91]:
print(data_4.loc[3, 'model_response'])

 Sure! Here's the JSON output based on your review:{    "Overall": "Positive",    "Food Quality": "Positive",    "Service": "Positive",    "Ambience": "Neutral",    "Food Quality Features": ["superb", "first-class"],    "Service Features": ["superb", "handling"],    "Ambience Features": [""]}Here's how I analyzed your review:* Overall: You mentioned that you had a "superb" experience at JW Marriott Hotel Aerocity, Delhi, which suggests a positive sentiment.* Food Quality: You praised the "first-class" food quality, which also suggests a positive sentiment.* Service: You appreciated the "superb" service you received, which further supports a positive sentiment.* Ambience: You did not mention anything specific about the ambience, so I have marked it as "Neutral".For each aspect, I've listed the liked features (in quotes) and disliked features (empty list), based on your review:* Food Quality Features: ["superb", "first-class"] (liked)* Service Features: ["superb", "handling"] (liked)* Ambience Features: ["] (no disliked features mentioned)Note that if you had mentioned any disliked features or aspects, I would have included them in the respective lists.

In [92]:
print(data_4.loc[6, 'model_response'])

    Sure! Here's my analysis of the review you provided:    {        "Overall": "Neutral",        "Food Quality": "Mixed",        "Service": "Positive",        "Ambience": "Positive",        "Food Quality Features": ["pullled duck was prepared and seasoned well but the meat had been marinated with too much balsamic vinegar"],        "Service Features": ["friendly and not intimidating"],        "Ambience Features": ["cozy feel"]    }Here's my analysis:* Overall: Neutral - The reviewer had mixed feelings about their experience at the restaurant.* Food Quality: Mixed - While the pulled duck was prepared and seasoned well, the meat was marinated too much in balsamic vinegar.* Service: Positive - The service was described as friendly and not intimidating.* Ambience: Positive - The reviewer enjoyed the cozy feel of the restaurant's ambience.Liked features:* Food Quality: prepared and seasoned well* Service: friendly* Ambience: cozy feelDisliked features:* Food Quality: too much balsamic vinegarI hope that helps! Let me know if you have any further questions or if you'd like me to analyze another review.

In [93]:
print(data_4.loc[7, 'model_response'])

    Sure! Here's the JSON output for the review you provided:{    "Overall": "Neutral",    "Food Quality": "Mixed",    "Service": "Slow",    "Ambience": "Not Applicable",    "Food Quality Features": ["mixed"],    "Service Features": ["slow"],    "Ambience Features": ["Not Applicable"]}Here's the breakdown:* Overall: Neutral - Based on the review, the reviewer had a neutral impression of their visit to Green Bites.* Food Quality: Mixed - While the reviewer mentions that the food quality is "mixed", they do not provide any specific liked or disliked features for this aspect.* Service: Slow - The reviewer notes that the service was slow, which contributes to the neutral sentiment for this aspect.* Ambience: Not Applicable - As the reviewer does not mention the ambience at all, this aspect is not applicable for this review.I hope this helps! Let me know if you have any further questions or if you'd like me to analyze any other reviews.

In [94]:
upd_val_1 = {
    "Overall": "Positive",
    "Food Quality": "Positive",
    "Service": "Positive",
    "Ambience": "Not Applicable",
    "Food Quality Features": [],
    "Service Features": ["excellent service"],
    "Ambience Features": []
}

upd_val_2 = {
    "Overall": "Neutral",
    "Food Quality": "Neutral",
    "Service": "Neutral",
    "Ambience": "Not Applicable",
    "Food Quality Features": ["well prepared"],
    "Service Features": ["slow and inattentive"],
    "Ambience Features": ["interior is friendly", "not intimidating"]
}

upd_val_3 = {
    "Overall": "Neutral",
    "Food Quality": "Positive",
    "Service": "Negative",
    "Ambience": "Positive",
    "Food Quality Features": ["Some tasty, others average"],
    "Service Features": ["Attentive staff", "Slow service"],
    "Ambience Features": []
}

idx_list = [3,6,7]
data_4.loc[idx_list, 'model_response_parsed'] = [upd_val_1, upd_val_2, upd_val_3]

In [95]:
model_response_parsed_df_4 = pd.json_normalize(data_4['model_response_parsed'])
model_response_parsed_df_4.head()

,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features
0,Positive,Positive,Positive,Positive,[straight from the oven],[staff wearing masks],[quite fancy]
1,Positive,Positive,Positive,Neutral,[exquisite taste],[freshly made],[]
2,Positive,Positive,Positive,Positive,[Excellent taste],[Great service],[Awesome decorum]
3,Positive,Positive,Positive,Not Applicable,[],[excellent service],[]
4,Positive,Positive,Positive,Neutral,[fabulous],[professional],[]

In [96]:
data_with_parsed_model_output_4 = pd.concat([data_4, model_response_parsed_df_4], axis=1)
data_with_parsed_model_output_4.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features
0,FLV202,5,"Totally in love with the Auro of the place, re...","{ ""Overall"": ""Positive"", ""Fo...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,[straight from the oven],[staff wearing masks],[quite fancy]
1,SAV303,5,Kailash colony is brimming with small cafes no...,Sure! Here's my analysis of your restauran...,"{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Neutral,[exquisite taste],[freshly made],[]
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"Sure, I can assist you in that! Here's my ana...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,[Excellent taste],[Great service],[Awesome decorum]
3,TST101,5,I have visited at jw lough/restourant. There w...,Sure! Here's the JSON output based on your re...,"{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Not Applicable,[],[excellent service],[]
4,EAT456,5,Had a great experience in the restaurant food ...,"{ ""Overall"": ""Positive"", ""Fo...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Neutral,[fabulous],[professional],[]

In [97]:
final_data_4 = data_with_parsed_model_output_4.drop(['model_response','model_response_parsed'], axis=1)
final_data_4.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive,Positive,Positive,Positive,[straight from the oven],[staff wearing masks],[quite fancy]
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive,Positive,Positive,Neutral,[exquisite taste],[freshly made],[]
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive,Positive,Positive,Positive,[Excellent taste],[Great service],[Awesome decorum]
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive,Positive,Positive,Not Applicable,[],[excellent service],[]
4,EAT456,5,Had a great experience in the restaurant food ...,Positive,Positive,Positive,Neutral,[fabulous],[professional],[]

In [98]:
final_data_4['Overall'].value_counts()

Overall
Neutral                      7
Positive                     6
Negative                     6
your_sentiment_prediction    1
Name: count, dtype: int64

In [99]:
final_data_4['Food Quality'].value_counts()

Food Quality
Positive                     8
Neutral                      7
Not Applicable               2
Mixed                        1
your_sentiment_prediction    1
Negative                     1
Name: count, dtype: int64

In [100]:
final_data_4['Service'].value_counts()

Service
Negative                     9
Positive                     8
Neutral                      1
Slow                         1
your_sentiment_prediction    1
Name: count, dtype: int64

In [101]:
final_data_4['Ambience'].value_counts()

Ambience
Positive                     6
Neutral                      6
Not Applicable               6
your_sentiment_prediction    1
Negative                     1
Name: count, dtype: int64

In [102]:
data_5 = data.copy()

In [103]:

instruction_5 = """
    You are an AI analyzing restaurant reviews. Classify the overall sentiment of the provided review into the following categories:
    - "Positive"
    - "Negative"
    - "Neutral"

    Once that is done, check for a mention of the following aspects in the review and clasify the sentiment of each aspect as positive, negative, or neutral:
    1. Food quality
    2. Service
    3. Ambience

    Once that is done, look for liked and/or disliked features mentioned against each of the above aspects in the review and extract them.

    Finally, draft a response for the customer based on the review. Start out with a thank you note and then add on to it as per the following:
    1. If the review is positive, mention that it would be great to have them again
    2. If the review is neutral, ask them for what the restaurant could have done better
    3. If the review is negative, apologive for the inconvenience and mention that we'll be looking into the points raised

    Return the output in the specified JSON format, ensuring consistency and handling missing values appropriately Ensure that all values in the JSON are formatted as strings, and each element within the lists should be enclosed in double quotes:

    {
        "Overall": "your_sentiment_prediction",
        "Food Quality": "your_sentiment_prediction",
        "Service": "your_sentiment_prediction",
        "Ambience": "your_sentiment_prediction",
        "Food Quality Features": ["liked/disliked features"],
        "Service Features": ["liked/disliked features"],
        "Ambience Features": ["liked/disliked features"],
        "Response": "your_response_to_the_customer_review",
    }

    The sentiment prediction for Overall, Food Quality, Service, and Ambience should be one of "Positive", "Negative", or "Neutral" only.
    In case one of the three aspects is not mentioned in the review, set "Not Applicable" (including quotes) in the corresponding JSON key value for the sentiment.
    In case there are no liked/disliked features for a particular aspect, assign an empty list in the corresponding JSON key value for the aspect.
    Be polite and empathetic in the response to the customer review.
    Only return the JSON, do NOT return any other text or information.
"""

In [104]:
data_5['model_response'] = data_5['review_full'].apply(lambda x: generate_llama_response(instruction_5, x))

Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     221.76 ms /   370 runs   (    0.60 ms per token,  1668.47 tokens per second)
llama_print_timings: prompt eval time =    1604.14 ms /   764 tokens (    2.10 ms per token,   476.27 tokens per second)
llama_print_timings:        eval time =   21705.61 ms /   369 runs   (   58.82 ms per token,    17.00 tokens per second)
llama_print_timings:       total time =   25177.67 ms /  1133 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     215.83 ms /   360 runs   (    0.60 ms per token,  1667.95 tokens per second)
llama_print_timings: prompt eval time =    1773.74 ms /   835 tokens (    2.12 ms per token,   470.76 tokens per second)
llama_print_timings:        eval time =   22453.04 ms /   359 runs   (   62.54 ms per token,    15.99 tokens per second)
llama_print_timings:       total time =   26062.60 ms /  1194 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      95.40 ms /   152 runs   (    0.63 ms per token,  1593.22 tokens per second)
llama_print_timings: prompt eval time =    1448.68 ms /   625 tokens (    2.32 ms per token,   431.43 tokens per second)
llama_print_timings:        eval time =    9462.26 ms /   151 runs   (   62.66 ms per token,    15.96 tokens per second)
llama_print_timings:       total time =   11679.71 ms /   776 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     112.59 ms /   187 runs   (    0.60 ms per token,  1660.92 tokens per second)
llama_print_timings: prompt eval time =    1616.32 ms /   735 tokens (    2.20 ms per token,   454.74 tokens per second)
llama_print_timings:        eval time =   11992.28 ms /   186 runs   (   64.47 ms per token,    15.51 tokens per second)
llama_print_timings:       total time =   14523.00 ms /   921 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     257.84 ms /   424 runs   (    0.61 ms per token,  1644.44 tokens per second)
llama_print_timings: prompt eval time =    1834.01 ms /   772 tokens (    2.38 ms per token,   420.94 tokens per second)
llama_print_timings:        eval time =   28062.87 ms /   423 runs   (   66.34 ms per token,    15.07 tokens per second)
llama_print_timings:       total time =   32118.55 ms /  1195 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     317.40 ms /   511 runs   (    0.62 ms per token,  1609.94 tokens per second)
llama_print_timings: prompt eval time =    1862.30 ms /   815 tokens (    2.29 ms per token,   437.63 tokens per second)
llama_print_timings:        eval time =   35166.01 ms /   510 runs   (   68.95 ms per token,    14.50 tokens per second)
llama_print_timings:       total time =   39698.99 ms /  1325 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     222.42 ms /   359 runs   (    0.62 ms per token,  1614.05 tokens per second)
llama_print_timings: prompt eval time =    1873.25 ms /   821 tokens (    2.28 ms per token,   438.28 tokens per second)
llama_print_timings:        eval time =   25086.97 ms /   358 runs   (   70.08 ms per token,    14.27 tokens per second)
llama_print_timings:       total time =   28762.73 ms /  1179 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     175.07 ms /   292 runs   (    0.60 ms per token,  1667.87 tokens per second)
llama_print_timings: prompt eval time =    1649.60 ms /   660 tokens (    2.50 ms per token,   400.10 tokens per second)
llama_print_timings:        eval time =   20345.42 ms /   291 runs   (   69.92 ms per token,    14.30 tokens per second)
llama_print_timings:       total time =   23407.23 ms /   951 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     255.70 ms /   429 runs   (    0.60 ms per token,  1677.75 tokens per second)
llama_print_timings: prompt eval time =    1666.84 ms /   662 tokens (    2.52 ms per token,   397.16 tokens per second)
llama_print_timings:        eval time =   30481.23 ms /   428 runs   (   71.22 ms per token,    14.04 tokens per second)
llama_print_timings:       total time =   34242.46 ms /  1090 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     192.10 ms /   327 runs   (    0.59 ms per token,  1702.22 tokens per second)
llama_print_timings: prompt eval time =    1672.63 ms /   661 tokens (    2.53 ms per token,   395.18 tokens per second)
llama_print_timings:        eval time =   23262.50 ms /   326 runs   (   71.36 ms per token,    14.01 tokens per second)
llama_print_timings:       total time =   26519.95 ms /   987 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     309.85 ms /   520 runs   (    0.60 ms per token,  1678.25 tokens per second)
llama_print_timings: prompt eval time =    1684.69 ms /   661 tokens (    2.55 ms per token,   392.36 tokens per second)
llama_print_timings:        eval time =   37383.08 ms /   519 runs   (   72.03 ms per token,    13.88 tokens per second)
llama_print_timings:       total time =   41719.58 ms /  1180 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     274.03 ms /   477 runs   (    0.57 ms per token,  1740.67 tokens per second)
llama_print_timings: prompt eval time =    1685.93 ms /   661 tokens (    2.55 ms per token,   392.07 tokens per second)
llama_print_timings:        eval time =   34689.60 ms /   476 runs   (   72.88 ms per token,    13.72 tokens per second)
llama_print_timings:       total time =   38733.36 ms /  1137 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      76.96 ms /   130 runs   (    0.59 ms per token,  1689.17 tokens per second)
llama_print_timings: prompt eval time =    1687.40 ms /   657 tokens (    2.57 ms per token,   389.36 tokens per second)
llama_print_timings:        eval time =    9262.19 ms /   129 runs   (   71.80 ms per token,    13.93 tokens per second)
llama_print_timings:       total time =   11560.10 ms /   786 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     260.75 ms /   412 runs   (    0.63 ms per token,  1580.03 tokens per second)
llama_print_timings: prompt eval time =    2145.07 ms /   963 tokens (    2.23 ms per token,   448.94 tokens per second)
llama_print_timings:        eval time =   30748.03 ms /   411 runs   (   74.81 ms per token,    13.37 tokens per second)
llama_print_timings:       total time =   35110.29 ms /  1374 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     152.10 ms /   244 runs   (    0.62 ms per token,  1604.19 tokens per second)
llama_print_timings: prompt eval time =    2734.61 ms /  1134 tokens (    2.41 ms per token,   414.68 tokens per second)
llama_print_timings:        eval time =   18273.65 ms /   243 runs   (   75.20 ms per token,    13.30 tokens per second)
llama_print_timings:       total time =   22299.54 ms /  1377 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     301.03 ms /   472 runs   (    0.64 ms per token,  1567.97 tokens per second)
llama_print_timings: prompt eval time =    2006.08 ms /   875 tokens (    2.29 ms per token,   436.17 tokens per second)
llama_print_timings:        eval time =   35187.05 ms /   471 runs   (   74.71 ms per token,    13.39 tokens per second)
llama_print_timings:       total time =   39706.73 ms /  1346 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     186.68 ms /   311 runs   (    0.60 ms per token,  1665.95 tokens per second)
llama_print_timings: prompt eval time =    2018.15 ms /   879 tokens (    2.30 ms per token,   435.55 tokens per second)
llama_print_timings:        eval time =   23191.64 ms /   310 runs   (   74.81 ms per token,    13.37 tokens per second)
llama_print_timings:       total time =   26803.92 ms /  1189 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     269.89 ms /   423 runs   (    0.64 ms per token,  1567.32 tokens per second)
llama_print_timings: prompt eval time =    2143.54 ms /   943 tokens (    2.27 ms per token,   439.93 tokens per second)
llama_print_timings:        eval time =   31705.18 ms /   422 runs   (   75.13 ms per token,    13.31 tokens per second)
llama_print_timings:       total time =   36123.20 ms /  1365 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =     157.70 ms /   271 runs   (    0.58 ms per token,  1718.46 tokens per second)
llama_print_timings: prompt eval time =    2640.16 ms /  1073 tokens (    2.46 ms per token,   406.42 tokens per second)
llama_print_timings:        eval time =   20346.14 ms /   270 runs   (   75.36 ms per token,    13.27 tokens per second)
llama_print_timings:       total time =   24326.66 ms /  1343 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1126.18 ms
llama_print_timings:      sample time =      97.56 ms /   156 runs   (    0.63 ms per token,  1598.93 tokens per second)
llama_print_timings: prompt eval time =    2061.11 ms /   896 tokens (    2.30 ms per token,   434.72 tokens per second)
llama_print_timings:        eval time =   11476.15 ms /   155 runs   (   74.04 ms per token,    13.51 tokens per second)
llama_print_timings:       total time =   14306.37 ms /  1051 tokens

In [105]:
i = 2
print(data_5.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [106]:
print(data_5.loc[i, 'model_response'])

 {
"Overall": "Positive",
"Food Quality": "Positive",
"Service": "Positive",
"Ambience": "Positive",
"Food Quality Features": ["Excellent taste"],
"Service Features": ["Great service"],
"Ambience Features": ["Awesome decorum"],
"Response": "Thank you for taking the time to share your positive review with us! We're thrilled to hear that you enjoyed our food quality, service, and ambience. We're constantly striving to improve, so your feedback is invaluable to us. We hope to have you back again soon!"]
}

In [107]:

data_5['model_response_parsed'] = data_5['model_response'].apply(extract_json_data)
data_5['model_response_parsed'].head()

Error parsing JSON: Expecting property name enclosed in double quotes: line 10 column 5 (char 539)
Error parsing JSON: Expecting ',' delimiter: line 9 column 277 (char 503)
Error parsing JSON: Expecting property name enclosed in double quotes: line 10 column 5 (char 579)
Error parsing JSON: Expecting property name enclosed in double quotes: line 10 column 5 (char 669)

0    {'Overall': 'Positive', 'Food Quality': 'Posit...
1                                                   {}
2                                                   {}
3    {'Overall': 'Positive', 'Food Quality': 'Posit...
4                                                   {}
Name: model_response_parsed, dtype: object

In [108]:
model_response_parsed_df_5 = pd.json_normalize(data_5['model_response_parsed'])
model_response_parsed_df_5.head()

,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features,Response
0,Positive,Positive,Positive,Positive,[straight from the oven],[quite delicious],[quite quaint and cute],Thank you for taking the time to review us! We...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Positive,Positive,Positive,Positive,[superb food],[superb service],[very nice ambience],Thank you so much for taking the time to revie...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
model_response_parsed_df_5['Response'][0]

"Thank you for taking the time to review us! We're thrilled to hear that you enjoyed our food quality, service, and ambience. We're especially glad that you appreciated our open kitchen concept and our use of disposable cutlery to ensure your safety during these challenging times. We hope to have you back again soon! If you have any further suggestions or feedback, please don't hesitate to reach out to us."

In [110]:
data_with_parsed_model_output_5 = pd.concat([data_5, model_response_parsed_df_5], axis=1)
data_with_parsed_model_output_5.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features,Response
0,FLV202,5,"Totally in love with the Auro of the place, re...","\n {\n ""Overall"": ""Positive"",\n ...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,[straight from the oven],[quite delicious],[quite quaint and cute],Thank you for taking the time to review us! We...
1,SAV303,5,Kailash colony is brimming with small cafes no...,"\n {\n ""Overall"": ""Positive"",\n ...",{},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{\n""Overall"": ""Positive"",\n""Food Quality"": ""P...",{},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TST101,5,I have visited at jw lough/restourant. There w...,"{\n ""Overall"": ""Positive"",\n ""F...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,[superb food],[superb service],[very nice ambience],Thank you so much for taking the time to revie...
4,EAT456,5,Had a great experience in the restaurant food ...,"\n {\n ""Overall"": ""Positive"",\n ...",{},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
final_data_5 = data_with_parsed_model_output_5.drop(['model_response','model_response_parsed'], axis=1)
final_data_5.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features,Response
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive,Positive,Positive,Positive,[straight from the oven],[quite delicious],[quite quaint and cute],Thank you for taking the time to review us! We...
1,SAV303,5,Kailash colony is brimming with small cafes no...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive,Positive,Positive,Positive,[superb food],[superb service],[very nice ambience],Thank you so much for taking the time to revie...
4,EAT456,5,Had a great experience in the restaurant food ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
final_data_5['Overall'].value_counts()

Overall
Neutral     9
Negative    5
Positive    2
Name: count, dtype: int64

In [113]:
final_data_5['Food Quality'].value_counts()

Food Quality
Neutral           9
Positive          3
Negative          2
Mixed             1
Not Applicable    1
Name: count, dtype: int64

In [114]:
final_data_5['Service'].value_counts()

Service
Negative    9
Positive    5
Neutral     2
Name: count, dtype: int64

In [115]:
final_data_5['Ambience'].value_counts()

Ambience
Neutral           10
Positive           4
Not Applicable     1
Negative           1
Name: count, dtype: int64